### ISSUE TITLE
Some mismatched diacritics

### ISSUE THREAD

**Issue by robinwhittleton** [vr8hub/leo-tolstoy_war-and-peace_louise-and-aylmer-maude#8]
Running `se find-mismatched-diacritics .` finds some potential problems (e.g. one occurrence of Amelie, everything else is Amélie). Can you review the output and fix anything that’s broken?

**Comment by vr8hub** [comment]
I think that's French vs non-French, but I’ll check again.

**Comment by vr8hub** [comment]
Fixed. (The remaining are all French vs non-French, or in one case German.)
